[package]
name = "unwind"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
libc = "0.2.119"
gimli = "0.26.1"
smallvec = "1.8.0"

[dev-dependencies]
nix = "0.23.1"
rand = "0.8.5"
backtrace = "0.3.64"

[build-dependencies]
cc = "1.0.73"
